---
- hosts: "{{target}}"
  remote_user: {{remote_user}}
  sudo: True
  vars:
    user: root
    graphite:
      secret_key: 'ob3sow^ik#4q(k5*tgw&6j+osyr^@0jus$yd+-#^&^d#%yim1!'
      nginx_server_name: www.monitoring.dev

    carbon:
      host: 0.0.0.0
      ssl: no
    db_graphite:
      name: graphite
      user: graphite
      password: graphite

  roles:
    - common
    - graphite
    - statsd
    - grafana

  tasks:
    - htpasswd: path=/etc/nginx/passwdfile name=admin password=admin owner=root group=www-data mode=0640
    - ufw: state=reset
    - ufw: state=enabled policy=allow
    - ufw: rule=reject port=auth log=yes
    - ufw: logging=on
    #- ufw: rule=allow proto=any src=X.X.X.X port=8125 log=yes insert=1
    #- ufw: rule=deny port=8125 proto=any log=yes insert=2
    #- ufw: rule=deny port=8126 proto=any log=yes insert=3

